name: awesome_widgets
description: Custom flutter widgets for awesome projects and apps.
version: 0.0.6
repository: https://github.com/abhishh1/awesome_widgets

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
